
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }

  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo4xQYlLTkZiY78XyLuJQzFl78MpL0qUU',
    appId: '1:164660568702:web:152f686abb27aade9b6e2f',
    messagingSenderId: '164660568702',
    projectId: 'petfinder-ba6f8',
    authDomain: 'petfinder-ba6f8.firebaseapp.com',
    storageBucket: 'petfinder-ba6f8.firebasestorage.app',
    measurementId: 'G-NJK3DG7KQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTXc2pEqO1sJXzwuHKyvtL4s1TKonGw5w',
    appId: '1:164660568702:android:2006ea45e7a925679b6e2f',
    messagingSenderId: '164660568702',
    projectId: 'petfinder-ba6f8',
    storageBucket: 'petfinder-ba6f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlXBoTZH7KREHFVvNCTKCRtq9F_gSuHFI',
    appId: '1:164660568702:ios:e17907f158fe94819b6e2f',
    messagingSenderId: '164660568702',
    projectId: 'petfinder-ba6f8',
    storageBucket: 'petfinder-ba6f8.firebasestorage.app',
    iosBundleId: 'com.example.gan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlXBoTZH7KREHFVvNCTKCRtq9F_gSuHFI',
    appId: '1:164660568702:ios:e17907f158fe94819b6e2f',
    messagingSenderId: '164660568702',
    projectId: 'petfinder-ba6f8',
    storageBucket: 'petfinder-ba6f8.firebasestorage.app',
    iosBundleId: 'com.example.gan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo4xQYlLTkZiY78XyLuJQzFl78MpL0qUU',
    appId: '1:164660568702:web:437da402723c91d99b6e2f',
    messagingSenderId: '164660568702',
    projectId: 'petfinder-ba6f8',
    authDomain: 'petfinder-ba6f8.firebaseapp.com',
    storageBucket: 'petfinder-ba6f8.firebasestorage.app',
    measurementId: 'G-5GJYLM9CDF',
  );
}
